services:
  powerdns:
    image: powerdns/pdns-auth-49:4.9.1
    command: [ "--local-port=8053" ]
    environment:
      PDNS_AUTH_API_KEY: secret
    ports:
      - 8081:8081
      - 8053:8053/udp
      - 8053:8053/tcp
